name: Build RSDKv5

on: workflow_dispatch

# each artifact is like 15MB so we'll start by only doing it manually
# on:
#   push:
#     branches:
#       - master

# TODO: readd with: submodules: recursive once we can

jobs:
  v5-windows:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: pkg-config make git mingw-w64-i686-gcc mingw-w64-i686-libogg mingw-w64-i686-libtheora
      - name: Build RSDKv5 + U
        run: |
          make -j8 RSDK_ONLY=1 AUTOBUILD=1
          make -j8 clean-rsdk
          make -j8 RSDK_ONLY=1 RSDK_REVISION=3 AUTOBUILD=1
      - name: Move artifacts
        run: |
          mkdir artifacts
          mv ./bin/Windows/DX9/*.exe ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: v5-windows
          path: artifacts
  v5-windows-x64:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: pkg-config make git mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-libogg mingw-w64-x86_64-libtheora
      - name: Build RSDKv5 + U
        run: |
          make -j8 RSDK_ONLY=1 AUTOBUILD=1
          make -j8 clean-rsdk
          make -j8 RSDK_ONLY=1 RSDK_REVISION=3 AUTOBUILD=1
      - name: Move artifacts
        run: |
          mkdir artifacts
          mv ./bin/Windows/DX9/*.exe ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: v5-windows-x64
          path: artifacts
  v5-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libogg-dev libsdl2-dev libtheora-dev libglew-dev libglfw3-dev
      - name: Build RSDKv5 + U OGL
        run: |
          make -j8 RSDK_ONLY=1 AUTOBUILD=1
          make -j8 clean-rsdk
          make -j8 RSDK_ONLY=1 RSDK_REVISION=3 AUTOBUILD=1
      - name: Build RSDKv5 + U SDL2
        run: |
          make -j8 RSDK_ONLY=1 SUBSYSTEM=SDL2 AUTOBUILD=1
          make -j8 clean-rsdk
          make -j8 RSDK_ONLY=1 SUBSYSTEM=SDL2 RSDK_REVISION=3 AUTOBUILD=1
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: v5-linux
          path: bin/Linux

  v5-macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2s
        with:
          submodules: recursive
      - name: Download libogg and libtheora for easier includes
        run: |
          curl "https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.5.zip" --output "libogg.zip"
          unzip libogg.zip -d ./dependencies/mac/
          mv ./dependencies/mac/libogg-1.3.5 ./dependencies/mac/libogg
          curl "https://downloads.xiph.org/releases/theora/libtheora-1.1.1.zips" --output "libtheora.zip"
          unzip libtheora.zip -d ./dependencies/mac/
          mv ./dependencies/mac/libtheora-1.1.1 ./dependencies/mac/libtheora
      - name: Download SDL2
        run: |
          curl "https://libsdl.org/release/SDL2-2.0.14.zip" --output "SDL2.zip"
          unzip SDL2.zip -d ./dependencies/mac/
          mv ./dependencies/mac/SDL2-2.0.14 ./dependencies/mac/SDL2
      - name: Generate Vorbis headers
        working-directory: ./dependencies/mac/libogg/
        run: |
          ./configure
      - name: Build RSDKv5
        run: |
          xcodebuild -project RSDKv5.xcodeproj -scheme RSDKv5 DSTROOT="./build" archive
      - name: Zip the app ourselves (Important step to retain symlinks)
        run: |
          cd ./build/Applications/
          zip -r RSDKv5.zip ./RSDKv5.app/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: v5-mac
          path: build/Applications/RSDKv5.zip
